print("so asik")
print("jangan ghosting")
print("mencintai dalam diam")
print("you know lah")
print("gamon")
print("overthingking")
print("yu bisa yu")
print("gacantik gadihargain")
print("insecure")
print("be yourself")